### ISSUE TITLE
Swuquery range matches whole plane

### ISSUE THREAD

**Issue by jpalm-openmind** [sutton-signwriting/core#6]
When using `swuquery.compose({ query: true, signbox: [{ range: ["񋨁", "񋨆"] }] })`, the resulting regex matches symbols outside the defined range in the same plane. I would expect that only symbols between the given range are matched.

See https://codesandbox.io/s/crazy-shape-rfl6i6?file=/src/index.js for an example.

**Comment by Slevinski** [comment]
This works as expected.  It is done this way to be consistent with FSW query strings.

Range matches use base symbols and ignore fill and rotation. 

So your first range in FSW is between S2f020 and S2f025.  In FSW Query, this would be written QR2f0t2f0.  This would match any symbol from the starting base symbol to the end base symbol regardless of fill or rotation.  As written this is the same as QS2f0uu in FSW and Q񋨡fr in SWU.

There isn't a way to specify searching for a range within a symbol base.  You can specify any fill or any rotation, but you can't specify only some rotations.  To achieve this, you would need to use OR searching such as QS2f020oS2f021oS2f022oS2f023oS2f024oS2f025  in FSW and Q񋨡o񋨢o񋨣o񋨤o񋨥o񋨦 in SWU.

**Comment by jpalm-openmind** [comment]
Thank you for the explanation.

This should probably be mentioned in the [swuquery.range](https://www.sutton-signwriting.io/core/#swuqueryrange) docs, though?

**Comment by Slevinski** [comment]
It should be mentioned.  I thought it was.  I'll update the docs for the next release.
