### ISSUE TITLE
Re-size sign

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/core#8]
Given a sign, for example `M500x500S1ce20491x485S2df00489x466` is there a function to correctly size the box?

**Comment by Slevinski** [comment]
You can get the size information for the sign using https://www.sutton-signwriting.io/core/#fswinfo but it looks like you want to adjust the max x,y coordinate.  For that you would need to use the normalize functions of font-ttf or font-db.

* https://www.sutton-signwriting.io/font-ttf/#fswsignnormalize
* https://www.sutton-signwriting.io/font-db/#fswsignnormalize

**Comment by AmitMY** [comment]
Perfect! Thank you <3
